nav:
  Home: /
  About: /about/
  Writing: /archives/
  Reading: /reading/
  Projects: https://github.com/jlouie95618

projects_url: /

customize:
    gravatar:
        email: 
    logo:
        enabled: false
        width: 50
        height: 50
        # url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        # url: /images/favicon.ico
        gravatar: false
      android:
        # url: /images/favicon-192x192.png
        gravator: false
      apple:
        # url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/jlouie95618
        # twitter: /
        # facebook: /
        linkedin: https://www.linkedin.com/in/john-louie-48239951/
        # stack-overflow: http://stackoverflow.com/users/4466524/jwlouie
        # hacker-news: https://news.ycombinator.com/user?id=jwlouie
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
